import {
  addPartyMemberAuthShabuduleHandler,
  checkIsFullShabuduleHandler,
  createPartyAuthShabuduleHandler,
  createPromotionShabuduleHandler,
  createShabuShopBranchShabuduleHandler,
  createShabuShopShabuduleHandler,
  createShabuShopTableShabuduleHandler,
  createUserAuthShabuduleHandler,
  createUserProfileAuthShabuduleHandler,
  deletePromotionShabuduleHandler,
  getAvailableSlotsShabuduleHandler,
  getBranchShabuduleHandler,
  getMyBookedTimeAuthShabuduleHandler,
  getMyJoinedPartyAuthShabuduleHandler,
  getMyPartyAuthShabuduleHandler,
  getPartyShabuduleHandler,
  getPromotionShabuduleHandler,
  getShopShabuduleHandler,
  getUserProfileAuthShabuduleHandler,
  updatePartyAuthShabuduleHandler,
  updatePartyMemberStatusAuthShabuduleHandler,
  updatePartyStatusAuthShabuduleHandler,
  updatePromotionShabuduleHandler,
  updateShabuShopBranchShabuduleHandler,
  updateShabuShopShabuduleHandler,
  updateUserBioAuthShabuduleHandler,
  updateUserCoverImageAuthShabuduleHandler,
  updateUserNameAuthShabuduleHandler,
  updateUserProfileImageAuthShabuduleHandler,
  updateUserTelAuthShabuduleHandler,
} from "./shabudule API";

export const AppRoutes = [
  {
    path: "/function/createUserAuthShabudule",
    method: "post",
    action: createUserAuthShabuduleHandler,
  },
  {
    path: "/function/createUserProfileAuthShabudule",
    method: "post",
    action: createUserProfileAuthShabuduleHandler,
  },
  {
    path: "/function/createPartyAuthShabudule",
    method: "post",
    action: createPartyAuthShabuduleHandler,
  },
  {
    path: "/function/addPartyMemberAuthShabudule",
    method: "post",
    action: addPartyMemberAuthShabuduleHandler,
  },
  {
    path: "/function/createShabuShopShabudule",
    method: "post",
    action: createShabuShopShabuduleHandler,
  },
  {
    path: "/function/createShabuShopBranchShabudule",
    method: "post",
    action: createShabuShopBranchShabuduleHandler,
  },
  {
    path: "/function/createShabuShopTableShabudule",
    method: "post",
    action: createShabuShopTableShabuduleHandler,
  },
  {
    path: "/function/createPromotionShabudule",
    method: "post",
    action: createPromotionShabuduleHandler,
  },
  {
    path: "/function/updatePartyMemberStatusAuthShabudule",
    method: "post",
    action: updatePartyMemberStatusAuthShabuduleHandler,
  },
  {
    path: "/function/updateShabuShopShabudule",
    method: "post",
    action: updateShabuShopShabuduleHandler,
  },
  {
    path: "/function/updateShabuShopBranchShabudule",
    method: "post",
    action: updateShabuShopBranchShabuduleHandler,
  },
  {
    path: "/function/updatePromotionShabudule",
    method: "post",
    action: updatePromotionShabuduleHandler,
  },
  {
    path: "/function/getPromotionShabudule",
    method: "post",
    action: getPromotionShabuduleHandler,
  },
  {
    path: "/function/getShopShabudule",
    method: "post",
    action: getShopShabuduleHandler,
  },
  {
    path: "/function/getBranchShabudule",
    method: "post",
    action: getBranchShabuduleHandler,
  },
  {
    path: "/function/getPartyShabudule",
    method: "post",
    action: getPartyShabuduleHandler,
  },
  {
    path: "/function/updatePartyAuthShabudule",
    method: "post",
    action: updatePartyAuthShabuduleHandler,
  },
  {
    path: "/function/getMyPartyAuthShabudule",
    method: "post",
    action: getMyPartyAuthShabuduleHandler,
  },
  {
    path: "/function/getMyJoinedPartyAuthShabudule",
    method: "post",
    action: getMyJoinedPartyAuthShabuduleHandler,
  },
  {
    path: "/function/updateUserNameAuthShabudule",
    method: "post",
    action: updateUserNameAuthShabuduleHandler,
  },
  {
    path: "/function/updateUserProfileImageAuthShabudule",
    method: "post",
    action: updateUserProfileImageAuthShabuduleHandler,
  },
  {
    path: "/function/updateUserCoverImageAuthShabudule",
    method: "post",
    action: updateUserCoverImageAuthShabuduleHandler,
  },
  {
    path: "/function/updateUserTelAuthShabudule",
    method: "post",
    action: updateUserTelAuthShabuduleHandler,
  },
  {
    path: "/function/updateUserBioAuthShabudule",
    method: "post",
    action: updateUserBioAuthShabuduleHandler,
  },
  {
    path: "/function/updatePartyStatusAuthShabudule",
    method: "post",
    action: updatePartyStatusAuthShabuduleHandler,
  },
  {
    path: "/function/deletePromotionShabudule",
    method: "post",
    action: deletePromotionShabuduleHandler,
  },
  {
    path: "/function/checkIsFullShabudule",
    method: "post",
    action: checkIsFullShabuduleHandler,
  },
  {
    path: "/function/getAvailableSlotsShabudule",
    method: "post",
    action: getAvailableSlotsShabuduleHandler,
  },
  {
    path: "/function/getUserProfileAuthShabudule",
    method: "post",
    action: getUserProfileAuthShabuduleHandler,
  },
  {
    path: "/function/getMyBookedTimeAuthShabudule",
    method: "post",
    action: getMyBookedTimeAuthShabuduleHandler,
  },
];
